### ISSUE TITLE
Many account?  

### ISSUE THREAD

**Issue by AQUIAL** [Shrinkvine/auto-vote-topgg#1]
Can you customize it to many accounts like config.js

**Comment by Shrinkvine** [comment]
You could do something like this: 
```js
async function voteForMyBot(user) {
  const { success, msg } = await vote(
    'https://top.gg/bot/123456789/vote',
    `C:\\Users\\${user}\\AppData\\Local\\Google\\Chrome\\User Data`,
  )
  console.log(success, msg)
}
```
and run it multiple times for each one that is logged in. Create a PR and add tokens if you'd like.

**If you create multiple chrome profiles, you can point the directory to each one, where each different profile is logged into a different account.**

**Comment by Shrinkvine** [comment]
You can now pass in your `connect.sid` cookie. Please update to version `1.0.13`
