### ISSUE TITLE
Option to configure headless mode [Suggestion]

### ISSUE THREAD

**Issue by Existential-nonce** [Shrinkvine/auto-vote-topgg#4]
Is it possible if you could add headless mode as a parameter in the `vote()` function?

I'm creating a project using your package and I need it to work on docker containers, so it needs to be headless. I initially tried creating a PR and this was my original modification:

```js
async function vote({ voteUrl, userDataDir, connectSidCookie, headlessOption }) {
  headlessOption == undefined ? headlessOption = false : null;
  if (typeof headlessOption != "boolean") { throw new Error("Please make the headlessOption parameter a boolean value!"); }
  let options = connectSidCookie ? { headless: headlessOption, ignoreDefaultArgs: ["--enable-automation"]  } : { headless: headlessOption, userDataDir, ignoreDefaultArgs: ["--enable-automation"] };

...

}
```
But it seems that it doesn't work as I'm not receiving any DMs from bots that would let you know for voting prizes (dankmemer, owo bot, pokemeow, etc...), it also returns `true` for `success` even though it hasn't worked. I'm sharing my portion as this might be helpful, idk lol.

**Comment by Shrinkvine** [comment]
Add me on discord and lets discuss NOT ME YOU#1300

**Comment by Existential-nonce** [comment]
Alright, sure
